var config = {
    prefix: "!",
    token: "NDQ3ODYxMTU3NTA0NDgzMzI4.DsC7HA.Tz8-FbiGHu922EbtsCtnVpxh0Bc",
    serverid: "447860330958159874",
    rainbowroles: "rainbow",
    rainbowrolesonoff:"on",
    muterol: "Mute",
    checkwordsonoff: "on",
    reportchannel: "reports",
    generalchatid: "448447480716328980",
    defaultrole: "NoName какой-то",
    defaultroleonoff: "off",
    chatlog: "on",
    welcome: "**привет!**\nОбязательно напиши мне команду !info!",
    welcomeonoff:"on",
    warningcount: "3",
    warningcountonoff:"on",
    automutetime: "6h",
    yt_api_key: "AIzaSyDkFneQ0Zt8r6nvvjnWuXEZpjcBWUR5h3k",
    channellog: 'commands',
    channellogonoff: 'on',
    modernamerole: 'Маленький ПИЗДЕЦ',
    tickenscategory: '508689966252163102'
}
module.exports = config;